// Cuando se modifique una funcionalidad importante de Mitynex, actualizar la sección correspondiente de este archivo para mantener la ayuda sincronizada.

export const helpPageContent = {
  eyebrow: 'Centro de aprendizaje',
  title: '¿Cómo podemos ayudarte?',
  subtitle: 'Busca una acción, revisa una guía rápida o pregunta al Asistente Mitynex.',
  searchPlaceholder: 'Buscar: trato, muestreo, proveedor, cosecha…',
  searchLabel: 'Buscar en el centro de ayuda',
  quickActionsTitle: '¿Qué necesitas hacer?',
  quickActionsSubtitle: 'Accede a las tareas más frecuentes y revisa sus pasos antes de comenzar.',
  guidedFlowsTitle: 'Guías rápidas',
  guidedFlowsSubtitle: 'Avanza paso a paso y completa una tarea sin perderte.',
  assistantTitle: 'Asistente Mitynex',
  assistantText: 'Pronto podrás preguntarle al asistente cómo usar cada módulo. Por ahora, selecciona una pregunta frecuente o guía rápida.',
  assistantBadge: 'Próximamente con IA',
  modulesTitle: 'Guías por módulo',
  modulesSubtitle: 'Una referencia compacta para conocer las funciones principales del sistema.',
  faqTitle: 'Preguntas frecuentes',
  noResultsTitle: 'No encontramos resultados',
  noResultsText: 'Prueba con otro término para encontrar una acción, guía o respuesta.',
  clearSearchLabel: 'Limpiar búsqueda',
  viewStepsLabel: 'Ver pasos',
  goToModuleLabel: 'Ir al módulo',
  previousLabel: 'Anterior',
  nextLabel: 'Siguiente',
  closeGuideLabel: 'Cerrar guía',
  stepLabel: 'Paso',
  ofLabel: 'de',
  exploreModuleLabel: 'Explorar módulo',
  lastUpdatedLabel: 'Actualizado',
};

export const quickActions = [
  {
    id: 'crear-trato',
    title: 'Crear un trato',
    description: 'Registra un acuerdo comercial con un proveedor.',
    route: '/gestion/tratos',
    guidedFlowId: 'crear-trato',
    icon: 'handshake',
  },
  {
    id: 'registrar-muestreo',
    title: 'Registrar muestreo',
    description: 'Guarda análisis, resultados y evidencia.',
    route: '/biomasa/muestreos',
    guidedFlowId: 'registrar-muestreo',
    icon: 'flask',
  },
  {
    id: 'programar-cosecha',
    title: 'Programar cosecha',
    description: 'Convierte un trato acordado en una planificación.',
    route: '/biomasa/programa',
    guidedFlowId: 'programar-cosecha',
    icon: 'calendar',
  },
  {
    id: 'revisar-trazabilidad',
    title: 'Revisar trazabilidad',
    description: 'Consulta acciones, responsables y actividad.',
    route: '/historial',
    guidedFlowId: 'revisar-historial',
    icon: 'history',
  },
  {
    id: 'reportar-problema',
    title: 'Reportar problema',
    description: 'Entrega contexto al equipo de soporte técnico.',
    action: 'support-report',
    guidedFlowId: 'reportar-problema',
    icon: 'bug',
  },
];

export const guidedFlows = [
  {
    id: 'crear-trato',
    title: 'Cómo crear un trato',
    description: 'Registra las condiciones principales de un acuerdo comercial.',
    route: '/gestion/tratos',
    icon: 'handshake',
    keywords: ['trato', 'proveedor', 'acuerdo', 'precio', 'toneladas'],
    steps: [
      { title: 'Abre Tratos', text: 'Entra a Tratos desde el grupo Operaciones del menú lateral.', visual: 'Navegación' },
      { title: 'Inicia el registro', text: 'Presiona Registrar trato y selecciona el proveedor correspondiente.', visual: 'Nuevo trato' },
      { title: 'Completa las condiciones', text: 'Ingresa producto, toneladas, precio e inicio probable.', visual: 'Condiciones' },
      { title: 'Revisa y guarda', text: 'Confirma los datos antes de guardar el trato.', visual: 'Confirmación' },
    ],
  },
  {
    id: 'registrar-muestreo',
    title: 'Cómo registrar un muestreo',
    description: 'Documenta el análisis y deja evidencia disponible para la operación.',
    route: '/biomasa/muestreos',
    icon: 'flask',
    keywords: ['muestreo', 'análisis', 'resultado', 'evidencia'],
    steps: [
      { title: 'Abre Muestreos', text: 'Entra a Muestreos desde el grupo Operaciones.', visual: 'Navegación' },
      { title: 'Selecciona el proveedor', text: 'Inicia un registro y elige el proveedor que fue muestreado.', visual: 'Proveedor' },
      { title: 'Completa el análisis', text: 'Ingresa contexto, resultados y evidencia disponible.', visual: 'Análisis' },
      { title: 'Guarda el resultado', text: 'Revisa la información y finaliza el registro.', visual: 'Resultado' },
    ],
  },
  {
    id: 'programar-cosecha',
    title: 'Cómo programar una cosecha',
    description: 'Planifica la ejecución de un trato acordado.',
    route: '/biomasa/programa',
    icon: 'calendar',
    keywords: ['programa', 'cosecha', 'calendario', 'camiones'],
    steps: [
      { title: 'Abre Programa de Cosecha', text: 'Entra a Prog. de Cosecha desde Operaciones.', visual: 'Navegación' },
      { title: 'Selecciona el trato', text: 'Crea un programa y vincúlalo con el trato acordado.', visual: 'Trato acordado' },
      { title: 'Define el ritmo', text: 'Configura días, transporte y ritmo diario de cosecha.', visual: 'Planificación' },
      { title: 'Revisa el calendario', text: 'Guarda y confirma la distribución planificada.', visual: 'Calendario' },
    ],
  },
  {
    id: 'revisar-historial',
    title: 'Cómo revisar historial',
    description: 'Encuentra eventos anteriores, responsables y actividad del equipo.',
    route: '/historial',
    icon: 'history',
    keywords: ['historial', 'trazabilidad', 'actividad', 'responsable'],
    steps: [
      { title: 'Abre Historial', text: 'Entra a Historial desde el grupo Trazabilidad.', visual: 'Navegación' },
      { title: 'Elige la vista', text: 'Revisa historial por proveedor o actividad del equipo.', visual: 'Vista' },
      { title: 'Busca información', text: 'Usa búsqueda y filtros para acotar los resultados.', visual: 'Filtros' },
      { title: 'Revisa el detalle', text: 'Consulta fechas, responsables y cambios registrados.', visual: 'Detalle' },
    ],
  },
  {
    id: 'reportar-problema',
    title: 'Cómo reportar un problema',
    description: 'Entrega información clara para facilitar la revisión técnica.',
    action: 'support-report',
    icon: 'bug',
    keywords: ['problema', 'error', 'soporte', 'reporte'],
    steps: [
      { title: 'Abre el reporte', text: 'Presiona Reportar problema en la parte inferior del menú lateral.', visual: 'Soporte' },
      { title: 'Describe lo ocurrido', text: 'Explica qué estabas haciendo y qué resultado esperabas.', visual: 'Descripción' },
      { title: 'Agrega contexto', text: 'Incluye el módulo, nombres o fechas relevantes sin datos sensibles.', visual: 'Contexto' },
      { title: 'Envía el reporte', text: 'Revisa el detalle y envíalo al equipo de soporte.', visual: 'Envío' },
    ],
  },
];

export const assistantPrompts = [
  { id: 'prompt-trato', label: '¿Cómo creo un trato?', guidedFlowId: 'crear-trato' },
  { id: 'prompt-muestreo', label: '¿Cómo registro un muestreo?', guidedFlowId: 'registrar-muestreo' },
  { id: 'prompt-problema', label: '¿Cómo reporto un problema?', guidedFlowId: 'reportar-problema' },
  { id: 'prompt-sin-muestreo', label: '¿Qué significa “Sin muestreo registrado”?', faqId: 'sin-muestreo' },
  { id: 'prompt-termino', label: '¿Cómo se calcula el término estimado?', faqId: 'termino-estimado' },
];

export const helpSections = [
  {
    id: 'primeros-pasos',
    title: 'Primeros pasos',
    route: null,
    summary: 'Navega por Mitynex, selecciona una empresa y encuentra las funciones principales.',
    whatYouCanDo: ['Moverte entre módulos.', 'Seleccionar una empresa.', 'Buscar proveedores o centros.', 'Reportar problemas.'],
    steps: ['Inicia sesión.', 'Selecciona una empresa si corresponde.', 'Abre un módulo desde el menú lateral.'],
    tips: ['La empresa seleccionada define los datos visibles.'],
    relatedFeatures: ['Menú lateral', 'Selector de empresa', 'Búsqueda global'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/dashboard',
    summary: 'Revisa indicadores, actividad reciente y alertas de la operación.',
    whatYouCanDo: ['Revisar indicadores.', 'Consultar actividad reciente.', 'Identificar alertas.'],
    steps: ['Entra a Dashboard.', 'Revisa indicadores y alertas.', 'Usa los accesos rápidos.'],
    tips: ['Presiona Actualizar para solicitar nuevamente los datos.'],
    relatedFeatures: ['Indicadores', 'Actividad reciente', 'Alertas'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'directorio',
    title: 'Directorio',
    route: '/gestion/proveedores',
    summary: 'Consulta proveedores, contactos y centros para apoyar la gestión.',
    whatYouCanDo: ['Buscar proveedores.', 'Consultar contactos.', 'Revisar centros.'],
    steps: ['Entra a Proveedores.', 'Busca por nombre.', 'Abre el registro para revisar sus datos.'],
    tips: ['Confirma la empresa seleccionada antes de buscar.'],
    relatedFeatures: ['Proveedores', 'Contactos', 'Centros'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'tratos',
    title: 'Tratos',
    route: '/gestion/tratos',
    summary: 'Registra acuerdos comerciales y consulta sus condiciones principales.',
    whatYouCanDo: ['Crear tratos.', 'Registrar toneladas y precio.', 'Compartir informes.'],
    steps: ['Entra a Tratos.', 'Presiona Registrar trato.', 'Completa y guarda la información.'],
    tips: ['El término estimado usa toneladas y camiones por día.'],
    relatedFeatures: ['Responsable automático', 'Término estimado', 'Informe público'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'programa-cosecha',
    title: 'Programa de Cosecha',
    route: '/biomasa/programa',
    summary: 'Organiza la ejecución de tratos acordados en un calendario operativo.',
    whatYouCanDo: ['Crear programas.', 'Definir ritmo diario.', 'Ajustar la planificación.'],
    steps: ['Abre Programa de Cosecha.', 'Selecciona un trato.', 'Define el ritmo y guarda.'],
    tips: ['Revisa saldo y fechas del trato antes de programar.'],
    relatedFeatures: ['Calendario', 'Seguimiento', 'Ajustes diarios'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'muestreos',
    title: 'Muestreos',
    route: '/biomasa/muestreos',
    summary: 'Registra análisis, resultados y evidencia para apoyar decisiones.',
    whatYouCanDo: ['Registrar muestreos.', 'Adjuntar evidencia.', 'Compartir informes.'],
    steps: ['Entra a Muestreos.', 'Selecciona proveedor.', 'Completa análisis y resultado.'],
    tips: ['Usa información verificable y revisa antes de guardar.'],
    relatedFeatures: ['Resultado', 'Evidencia', 'Informe público'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'biomasa',
    title: 'Biomasa',
    route: '/biomasa/status',
    summary: 'Consulta disponibilidad, asignaciones y estado de biomasa.',
    whatYouCanDo: ['Revisar disponibilidad.', 'Consultar asignaciones.', 'Comparar periodos.'],
    steps: ['Entra a Biomasa.', 'Selecciona vista y periodo.', 'Revisa los registros.'],
    tips: ['Mantén tratos, programas y muestreos actualizados.'],
    relatedFeatures: ['Disponibilidad', 'Asignaciones', 'Programas'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'trazabilidad',
    title: 'Trazabilidad',
    route: '/historial',
    summary: 'Revisa qué ocurrió, cuándo ocurrió y quién estuvo asociado.',
    whatYouCanDo: ['Consultar historial.', 'Revisar actividad del equipo.', 'Identificar responsables.'],
    steps: ['Abre Historial.', 'Elige una vista.', 'Busca y revisa el detalle.'],
    tips: ['Registra acciones oportunamente para mantener la trazabilidad.'],
    relatedFeatures: ['Historial', 'Actividad del equipo', 'Sanitario'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'soporte-tecnico',
    title: 'Soporte técnico',
    route: null,
    summary: 'Reporta problemas y entrega contexto para facilitar su revisión.',
    whatYouCanDo: ['Reportar problemas.', 'Describir lo ocurrido.', 'Entregar contexto útil.'],
    steps: ['Presiona Reportar problema.', 'Describe lo ocurrido.', 'Envía el reporte.'],
    tips: ['Evita incluir información sensible.'],
    relatedFeatures: ['Reporte de problemas', 'Panel de soporte'],
    lastUpdated: '2026-06-10',
  },
];

export const helpFaqs = [
  {
    id: 'proveedor-no-encontrado',
    question: '¿Qué hago si no encuentro un proveedor?',
    answer: 'Confirma la empresa seleccionada, busca usando solo una parte del nombre y revisa la ortografía.',
    relatedSectionId: 'directorio',
  },
  {
    id: 'sin-muestreo',
    question: '¿Qué significa “Sin muestreo registrado”?',
    answer: 'Indica que Mitynex no encuentra un muestreo asociado disponible para ese proveedor o registro.',
    relatedSectionId: 'muestreos',
  },
  {
    id: 'reportar-problema',
    question: '¿Cómo reporto un problema?',
    answer: 'Presiona Reportar problema en la parte inferior del menú lateral y describe qué ocurrió.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'panel-soporte',
    question: '¿Quién puede ver el panel de soporte técnico?',
    answer: 'El panel está disponible únicamente para los roles autorizados definidos por Mitynex.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'datos-automaticos',
    question: '¿Por qué algunos datos se calculan automáticamente?',
    answer: 'Mitynex usa los datos registrados para evitar cálculos repetidos y mantener criterios consistentes.',
    relatedSectionId: 'primeros-pasos',
  },
  {
    id: 'termino-estimado',
    question: '¿Cómo se calcula el término estimado de un trato?',
    answer: 'Se estima usando las toneladas registradas y el ritmo de camiones por día.',
    relatedSectionId: 'tratos',
  },
  {
    id: 'significado-trazabilidad',
    question: '¿Qué significa Trazabilidad?',
    answer: 'Es la capacidad de revisar qué ocurrió, cuándo ocurrió y quién estuvo asociado a una acción.',
    relatedSectionId: 'trazabilidad',
  },
];
