// Cuando se modifique una funcionalidad importante de Mitynex, actualizar la sección correspondiente de este archivo para mantener la ayuda sincronizada.

export const helpPageContent = {
  eyebrow: 'Centro de ayuda',
  title: 'Ayuda y guía de Mitynex',
  subtitle: 'Aprende a usar los módulos principales y resuelve dudas frecuentes del sistema.',
  searchPlaceholder: 'Buscar en la ayuda...',
  moduleFilterLabel: 'Saltar a un módulo',
  allModulesLabel: 'Todos los módulos',
  quickActionsTitle: 'Accesos rápidos',
  modulesTitle: 'Guías por módulo',
  modulesSubtitle: 'Selecciona una tarjeta para revisar sus funciones, pasos recomendados y consejos.',
  faqTitle: 'Preguntas frecuentes',
  noResultsTitle: 'No encontramos resultados',
  noResultsText: 'Prueba con otro término o vuelve a mostrar todos los módulos.',
  clearSearchLabel: 'Limpiar búsqueda',
  whatYouCanDoLabel: 'Qué puedes hacer',
  stepsLabel: 'Cómo usarlo',
  tipsLabel: 'Consejos',
  relatedFeaturesLabel: 'Funciones relacionadas',
  goToModuleLabel: 'Ir al módulo',
  lastUpdatedLabel: 'Última actualización',
  showDetailsLabel: 'Ver guía',
  hideDetailsLabel: 'Ocultar guía',
};

export const helpQuickActions = [
  {
    id: 'dashboard',
    label: 'Abrir Dashboard',
    description: 'Revisa el estado general de la operación.',
    route: '/dashboard',
  },
  {
    id: 'directorio',
    label: 'Buscar proveedor',
    description: 'Consulta proveedores y sus datos de contacto.',
    route: '/gestion/proveedores',
  },
  {
    id: 'tratos',
    label: 'Revisar Tratos',
    description: 'Consulta acuerdos comerciales registrados.',
    route: '/gestion/tratos',
  },
  {
    id: 'reportar',
    label: 'Reportar un problema',
    description: 'Envía el detalle de un problema al equipo de soporte.',
    action: 'support-report',
  },
];

export const helpSections = [
  {
    id: 'primeros-pasos',
    title: 'Primeros pasos',
    route: null,
    summary: 'Conoce la navegación principal y prepara el contexto necesario para trabajar en Mitynex.',
    whatYouCanDo: [
      'Moverte entre módulos desde el menú lateral.',
      'Seleccionar una empresa cuando tu perfil administra más de una.',
      'Usar la búsqueda lateral para encontrar proveedores o centros.',
      'Reportar un problema desde cualquier pantalla.',
    ],
    steps: [
      'Inicia sesión con tu cuenta de Mitynex.',
      'Si aparece el selector de empresa, elige la empresa con la que trabajarás.',
      'Abre un grupo del menú lateral y selecciona el módulo que necesitas.',
      'Verifica el título de la pantalla antes de registrar o modificar información.',
    ],
    tips: [
      'La empresa seleccionada define los datos visibles en los módulos operativos.',
      'Puedes volver al Dashboard para recuperar una vista general de la operación.',
    ],
    relatedFeatures: ['Menú lateral', 'Selector de empresa', 'Búsqueda global', 'Reporte de problemas'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/dashboard',
    summary: 'Entrega una vista general de la operación, biomasa, actividad reciente y alertas.',
    whatYouCanDo: [
      'Revisar indicadores principales de la operación.',
      'Consultar actividad reciente.',
      'Identificar alertas sanitarias.',
      'Usar accesos rápidos a módulos operativos.',
    ],
    steps: [
      'Entra a Dashboard desde Inicio.',
      'Revisa los indicadores del periodo mostrado.',
      'Consulta la actividad reciente y las alertas disponibles.',
      'Usa un acceso rápido para continuar en el módulo correspondiente.',
    ],
    tips: [
      'Presiona Actualizar para solicitar nuevamente los datos visibles.',
      'Los indicadores resumen información registrada en otros módulos.',
    ],
    relatedFeatures: ['Indicadores', 'Actividad reciente', 'Alertas sanitarias', 'Accesos rápidos'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'directorio',
    title: 'Directorio',
    route: '/gestion/proveedores',
    summary: 'Centraliza proveedores, contactos y centros para apoyar la gestión comercial y operativa.',
    whatYouCanDo: [
      'Buscar proveedores y revisar sus antecedentes.',
      'Registrar y consultar contactos asociados.',
      'Revisar centros desde el directorio o el mapa.',
      'Iniciar acciones de seguimiento desde la información disponible.',
    ],
    steps: [
      'Entra a Proveedores desde Directorio.',
      'Busca al proveedor por nombre usando el campo disponible.',
      'Abre su información para revisar contactos y antecedentes.',
      'Si necesitas un centro, entra a Centros desde el mismo grupo lateral.',
    ],
    tips: [
      'Confirma que estás trabajando con la empresa correcta antes de buscar.',
      'Si no encuentras un proveedor, prueba una parte del nombre y revisa la ortografía.',
    ],
    relatedFeatures: ['Proveedores', 'Contactos', 'Centros', 'Mapa de centros'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'tratos',
    title: 'Tratos',
    route: '/gestion/tratos',
    summary: 'Permite registrar acuerdos comerciales con proveedores y seguir sus condiciones principales.',
    whatYouCanDo: [
      'Crear tratos por proveedor.',
      'Registrar producto, toneladas y precio.',
      'Ver responsable y término estimado.',
      'Compartir un informe público del trato.',
    ],
    steps: [
      'Entra a Tratos.',
      'Presiona Registrar trato.',
      'Selecciona proveedor.',
      'Completa producto, toneladas, precio e inicio probable.',
      'Guarda el trato.',
    ],
    tips: [
      'El responsable se asigna automáticamente desde el usuario conectado.',
      'El término estimado se calcula según toneladas y camiones por día.',
    ],
    relatedFeatures: ['Responsable automático', 'Término estimado', 'Informe público'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'programa-cosecha',
    title: 'Programa de Cosecha',
    route: '/biomasa/programa',
    summary: 'Organiza la ejecución de tratos acordados mediante programas, ritmos diarios y calendario.',
    whatYouCanDo: [
      'Crear programas asociados a tratos acordados.',
      'Definir producto, transporte y ritmo diario.',
      'Revisar la planificación en calendario.',
      'Ajustar, pausar o finalizar programas según la operación.',
    ],
    steps: [
      'Entra a Prog. de Cosecha desde Operaciones.',
      'Crea un programa y selecciona el trato correspondiente.',
      'Define días, transporte y ritmo de cosecha.',
      'Guarda y revisa la distribución en el calendario.',
    ],
    tips: [
      'Revisa el saldo y las fechas del trato antes de programar.',
      'Registra los ajustes del día para mantener la planificación actualizada.',
    ],
    relatedFeatures: ['Calendario', 'Seguimiento', 'Ajustes diarios', 'Tratos acordados'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'muestreos',
    title: 'Muestreos',
    route: '/biomasa/muestreos',
    summary: 'Registra resultados de muestreo y evidencia para apoyar decisiones de compra y cosecha.',
    whatYouCanDo: [
      'Registrar un muestreo para un proveedor.',
      'Ingresar resultados y antecedentes del análisis.',
      'Adjuntar evidencia disponible.',
      'Compartir un informe público del muestreo.',
    ],
    steps: [
      'Entra a Muestreos desde Operaciones.',
      'Inicia un nuevo registro y selecciona el proveedor.',
      'Completa contexto, análisis y resultado.',
      'Revisa la información y guarda el muestreo.',
    ],
    tips: [
      'Usa información verificable para que el resultado sea útil en otros módulos.',
      'Comparte el informe público cuando otra persona necesite revisar el resultado.',
    ],
    relatedFeatures: ['Resultado', 'Evidencia', 'Informe público', 'Programa de Cosecha'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'biomasa',
    title: 'Biomasa',
    route: '/biomasa/status',
    summary: 'Consolida disponibilidad, asignaciones y estado de biomasa para apoyar la planificación.',
    whatYouCanDo: [
      'Revisar disponibilidad de biomasa.',
      'Consultar biomasa asignada.',
      'Comparar información por periodo.',
      'Relacionar la disponibilidad con programas y tratos.',
    ],
    steps: [
      'Entra al estado de Biomasa.',
      'Selecciona la vista y el periodo que necesitas revisar.',
      'Consulta los indicadores y registros disponibles.',
      'Contrasta la información con programas y muestreos cuando corresponda.',
    ],
    tips: [
      'Mantén tratos, programas y muestreos actualizados para mejorar la lectura operativa.',
      'Un registro sin muestreo indica que no existe un muestreo asociado disponible.',
    ],
    relatedFeatures: ['Disponibilidad', 'Asignaciones', 'Programas', 'Muestreos'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'trazabilidad',
    title: 'Trazabilidad',
    route: '/historial',
    summary: 'Permite revisar lo que ocurrió, quién realizó acciones y cómo evolucionó la operación.',
    whatYouCanDo: [
      'Consultar el historial por proveedor.',
      'Revisar actividad reciente del equipo.',
      'Identificar responsables y fechas de registros.',
      'Consultar el estado sanitario de centros.',
    ],
    steps: [
      'Abre Trazabilidad desde el menú lateral.',
      'Entra a Historial para revisar eventos y actividad del equipo.',
      'Busca o filtra la información que necesitas.',
      'Abre Sanitario cuando necesites revisar alertas de centros.',
    ],
    tips: [
      'La trazabilidad depende de que las acciones se registren oportunamente.',
      'Usa fechas y responsables para entender el origen de cada cambio.',
    ],
    relatedFeatures: ['Historial', 'Actividad del equipo', 'Responsables', 'Sanitario'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'soporte-tecnico',
    title: 'Soporte técnico',
    route: null,
    summary: 'Facilita el reporte de problemas y la revisión técnica por parte de usuarios autorizados.',
    whatYouCanDo: [
      'Reportar un problema desde el menú lateral.',
      'Describir qué estabas haciendo cuando ocurrió.',
      'Entregar información útil para facilitar la revisión.',
      'Revisar reportes técnicos si tu rol tiene acceso.',
    ],
    steps: [
      'Presiona Reportar problema en la parte inferior del menú lateral.',
      'Describe el problema y los pasos que realizaste.',
      'Incluye el resultado esperado y lo que ocurrió.',
      'Envía el reporte para que soporte pueda revisarlo.',
    ],
    tips: [
      'Incluye nombres, fechas y módulo afectado, evitando información sensible.',
      'El panel de soporte técnico solo está visible para roles autorizados.',
    ],
    relatedFeatures: ['Reporte de problemas', 'Panel de soporte técnico', 'Detalle del error'],
    lastUpdated: '2026-06-10',
  },
];

export const helpFaqs = [
  {
    id: 'proveedor-no-encontrado',
    question: '¿Qué hago si no encuentro un proveedor?',
    answer: 'Confirma la empresa seleccionada, busca usando solo una parte del nombre y revisa la ortografía. Si aún no aparece, solicita a un usuario autorizado que confirme si el proveedor está registrado.',
    relatedSectionId: 'directorio',
  },
  {
    id: 'sin-muestreo',
    question: '¿Qué significa “Sin muestreo registrado”?',
    answer: 'Indica que Mitynex no encuentra un muestreo asociado disponible para ese proveedor o registro. Puedes revisar Muestreos para confirmar si corresponde crear o completar uno.',
    relatedSectionId: 'muestreos',
  },
  {
    id: 'reportar-problema',
    question: '¿Cómo reporto un problema?',
    answer: 'Presiona Reportar problema en la parte inferior del menú lateral, describe qué estabas haciendo, qué esperabas y qué ocurrió, y luego envía el reporte.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'panel-soporte',
    question: '¿Quién puede ver el panel de soporte técnico?',
    answer: 'El panel de soporte técnico está disponible únicamente para los roles autorizados definidos por Mitynex. Reportar un problema sigue disponible desde el menú lateral.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'datos-automaticos',
    question: '¿Por qué algunos datos se calculan automáticamente?',
    answer: 'Mitynex usa los datos registrados para evitar cálculos repetidos y mantener criterios consistentes. Revisa siempre los datos de origen si un resultado no coincide con lo esperado.',
    relatedSectionId: 'primeros-pasos',
  },
  {
    id: 'termino-estimado',
    question: '¿Cómo se calcula el término estimado de un trato?',
    answer: 'Se estima usando las toneladas registradas y el ritmo de camiones por día. Si cambian esos datos, el término estimado también puede cambiar.',
    relatedSectionId: 'tratos',
  },
  {
    id: 'significado-trazabilidad',
    question: '¿Qué significa Trazabilidad?',
    answer: 'Es la capacidad de revisar qué ocurrió, cuándo ocurrió y quién estuvo asociado a una acción o registro dentro de la operación.',
    relatedSectionId: 'trazabilidad',
  },
];
