// Cuando se modifique una funcionalidad importante de Mitynex, actualizar la sección correspondiente de este archivo para mantener la ayuda sincronizada.

export const helpPageContent = {
  eyebrow: 'Centro de aprendizaje',
  title: '¿Cómo podemos ayudarte?',
  subtitle: 'Busca una acción, revisa una guía rápida o pregunta al Asistente Mitynex.',
  searchPlaceholder: 'Buscar: trato, muestreo, proveedor, cosecha…',
  searchLabel: 'Buscar en el centro de ayuda',
  quickActionsTitle: '¿Qué necesitas hacer?',
  quickActionsSubtitle: 'Accede a las tareas más frecuentes y revisa sus pasos antes de comenzar.',
  guidedFlowsTitle: 'Guías rápidas',
  guidedFlowsSubtitle: 'Avanza paso a paso y completa una tarea sin perderte.',
  assistantTitle: 'Asistente Mitynex',
  assistantText: 'Selecciona una pregunta y te llevaremos directo a la guía correcta. Próximamente podrás preguntarle al asistente en lenguaje natural.',
  assistantBadge: 'Próximamente con IA',
  modulesTitle: 'Guías por módulo',
  modulesSubtitle: 'Una referencia compacta para conocer las funciones principales del sistema.',
  faqTitle: 'Preguntas frecuentes',
  noResultsTitle: 'No encontramos resultados',
  noResultsText: 'Prueba con otro término para encontrar una acción, guía o respuesta.',
  clearSearchLabel: 'Limpiar búsqueda',
  viewStepsLabel: 'Ver pasos',
  goToModuleLabel: 'Ir al módulo',
  previousLabel: 'Anterior',
  nextLabel: 'Siguiente',
  closeGuideLabel: 'Cerrar guía',
  stepLabel: 'Paso',
  ofLabel: 'de',
  exploreModuleLabel: 'Explorar módulo',
  lastUpdatedLabel: 'Actualizado',
};

export const quickActions = [
  {
    id: 'crear-trato',
    title: 'Crear un trato',
    description: 'Registra un acuerdo comercial con un proveedor.',
    route: '/gestion/tratos',
    guidedFlowId: 'crear-trato',
    icon: 'handshake',
  },
  {
    id: 'registrar-muestreo',
    title: 'Registrar muestreo',
    description: 'Guarda análisis, resultados y evidencia.',
    route: '/biomasa/muestreos',
    guidedFlowId: 'registrar-muestreo',
    icon: 'flask',
  },
  {
    id: 'programar-cosecha',
    title: 'Programar cosecha',
    description: 'Convierte un trato acordado en una planificación.',
    route: '/biomasa/programa',
    guidedFlowId: 'programar-cosecha',
    icon: 'calendar',
  },
  {
    id: 'revisar-trazabilidad',
    title: 'Revisar trazabilidad',
    description: 'Consulta acciones, responsables y actividad.',
    route: '/historial',
    guidedFlowId: 'revisar-historial',
    icon: 'history',
  },
  {
    id: 'reportar-problema',
    title: 'Reportar problema',
    description: 'Entrega contexto al equipo de soporte técnico.',
    action: 'support-report',
    guidedFlowId: 'reportar-problema',
    icon: 'bug',
  },
];

export const guidedFlows = [
  {
    id: 'crear-trato',
    title: 'Cómo crear un trato',
    description: 'Registra las condiciones principales de un acuerdo comercial.',
    route: '/gestion/tratos',
    icon: 'handshake',
    image: null,
    keywords: ['trato', 'proveedor', 'acuerdo', 'precio', 'toneladas'],
    steps: [
      { title: 'Ve a Operaciones', text: 'En el menú lateral, abre la sección Operaciones.', visualHint: 'sidebar-operaciones', image: null },
      { title: 'Abre Tratos', text: 'Selecciona Tratos para ver los acuerdos comerciales registrados.', visualHint: 'modulo-tratos', image: null },
      { title: 'Presiona Registrar', text: 'Usa el botón Registrar para abrir el formulario de nuevo trato.', visualHint: 'boton-registrar', image: null },
      { title: 'Completa los datos principales', text: 'Selecciona proveedor, producto, toneladas, precio e inicio probable.', visualHint: 'formulario-trato', image: null },
      { title: 'Revisa responsable y término estimado', text: 'El sistema asigna el responsable desde tu usuario y calcula el término estimado.', visualHint: 'calculo-trato', image: null },
      { title: 'Guarda y comparte', text: 'Guarda el trato y usa el informe público si necesitas enviarlo.', visualHint: 'guardar-compartir', image: null },
    ],
  },
  {
    id: 'registrar-muestreo',
    title: 'Cómo registrar un muestreo',
    description: 'Documenta el análisis y deja evidencia disponible para la operación.',
    route: '/biomasa/muestreos',
    icon: 'flask',
    image: null,
    keywords: ['muestreo', 'análisis', 'resultado', 'evidencia'],
    steps: [
      { title: 'Ve a Muestreos', text: 'En el menú lateral, abre Operaciones y selecciona Muestreos. También puedes llegar desde Biomasa según la navegación disponible.', visualHint: 'sidebar-muestreos', image: null },
      { title: 'Abre Muestreos', text: 'Revisa los registros existentes antes de iniciar uno nuevo.', visualHint: 'modulo-muestreos', image: null },
      { title: 'Presiona Registrar muestreo', text: 'Usa el botón Registrar muestreo para abrir el formulario.', visualHint: 'boton-registrar-muestreo', image: null },
      { title: 'Selecciona proveedor y centro', text: 'Elige el proveedor y, cuando corresponda, el centro asociado al muestreo.', visualHint: 'formulario-proveedor-centro', image: null },
      { title: 'Ingresa los resultados', text: 'Completa U/Kg, rendimiento, rechazo, condición y observaciones.', visualHint: 'formulario-muestreo', image: null },
      { title: 'Adjunta evidencias', text: 'Agrega imágenes o antecedentes disponibles cuando aporten contexto al resultado.', visualHint: 'evidencia', image: null },
      { title: 'Guarda el muestreo', text: 'Revisa la información ingresada y guarda el registro.', visualHint: 'guardar', image: null },
    ],
  },
  {
    id: 'programar-cosecha',
    title: 'Cómo programar una cosecha',
    description: 'Planifica la ejecución de un trato acordado.',
    route: '/biomasa/programa',
    icon: 'calendar',
    image: null,
    keywords: ['programa', 'cosecha', 'calendario', 'camiones'],
    steps: [
      { title: 'Ve a Operaciones', text: 'En el menú lateral, abre la sección Operaciones.', visualHint: 'sidebar-operaciones', image: null },
      { title: 'Abre Programa de Cosecha', text: 'Selecciona Prog. de Cosecha. También puedes acceder desde Biomasa según la navegación disponible.', visualHint: 'modulo-programa', image: null },
      { title: 'Selecciona proveedor y producto', text: 'Elige el trato, proveedor y producto que quieres programar.', visualHint: 'formulario-programa', image: null },
      { title: 'Define cosecha y transporte', text: 'Selecciona los días de cosecha y configura el transporte requerido.', visualHint: 'calendario-transporte', image: null },
      { title: 'Revisa la estimación', text: 'Confirma toneladas, camiones y fecha de término estimada antes de guardar.', visualHint: 'resumen-programa', image: null },
      { title: 'Guarda el programa', text: 'Guarda la planificación para verla en el calendario operativo.', visualHint: 'guardar', image: null },
      { title: 'Ajusta cuando sea necesario', text: 'Usa Ajustar si necesitas sumar, descontar o suspender un día.', visualHint: 'boton-ajustar', image: null },
    ],
  },
  {
    id: 'revisar-historial',
    title: 'Cómo revisar historial',
    description: 'Encuentra eventos anteriores, responsables y actividad del equipo.',
    route: '/historial',
    icon: 'history',
    image: null,
    keywords: ['historial', 'trazabilidad', 'actividad', 'responsable'],
    steps: [
      { title: 'Ve a Trazabilidad', text: 'En el menú lateral, abre la sección Trazabilidad.', visualHint: 'sidebar-trazabilidad', image: null },
      { title: 'Abre Historial', text: 'Selecciona Historial para revisar la actividad registrada.', visualHint: 'modulo-historial', image: null },
      { title: 'Busca proveedor o centro', text: 'Usa el buscador para encontrar el proveedor o centro que necesitas revisar.', visualHint: 'buscador', image: null },
      { title: 'Revisa la actividad relacionada', text: 'Consulta eventos, muestreos, tratos y responsables asociados.', visualHint: 'actividad', image: null },
      { title: 'Usa los filtros', text: 'Aplica filtros para encontrar información específica con mayor rapidez.', visualHint: 'filtros', image: null },
    ],
  },
  {
    id: 'reportar-problema',
    title: 'Cómo reportar un problema',
    description: 'Entrega información clara para facilitar la revisión técnica.',
    action: 'support-report',
    actionLabel: 'Abrir reporte',
    icon: 'bug',
    image: null,
    keywords: ['problema', 'error', 'soporte', 'reporte'],
    steps: [
      { title: 'Abre Reportar problema', text: 'Presiona Reportar problema en la parte inferior del menú lateral.', visualHint: 'soporte', image: null },
      { title: 'Describe tu objetivo', text: 'Explica qué estabas intentando hacer cuando apareció el problema.', visualHint: 'formulario-soporte-objetivo', image: null },
      { title: 'Explica qué ocurrió', text: 'Describe el resultado que viste y cualquier mensaje relevante.', visualHint: 'formulario-soporte-ocurrido', image: null },
      { title: 'Indica qué esperabas', text: 'Explica brevemente cuál era el resultado esperado.', visualHint: 'formulario-soporte-esperado', image: null },
      { title: 'Selecciona la urgencia', text: 'Indica la urgencia para ayudar a priorizar la revisión.', visualHint: 'urgencia', image: null },
      { title: 'Envía el reporte', text: 'Envía el reporte. El sistema agregará contexto técnico automáticamente.', visualHint: 'enviar-reporte', image: null },
    ],
  },
];

export const visualHints = {
  'sidebar-operaciones': { type: 'sidebar', eyebrow: 'Menú lateral', items: ['Inicio', 'Operaciones', 'Directorio'], active: 'Operaciones' },
  'sidebar-muestreos': { type: 'sidebar', eyebrow: 'Operaciones', items: ['Tratos', 'Prog. de Cosecha', 'Muestreos'], active: 'Muestreos' },
  'sidebar-trazabilidad': { type: 'sidebar', eyebrow: 'Menú lateral', items: ['Directorio', 'Trazabilidad', 'Ayuda'], active: 'Trazabilidad' },
  'modulo-tratos': { type: 'module', eyebrow: 'Operaciones', title: 'Tratos', detail: 'Acuerdos comerciales registrados' },
  'modulo-muestreos': { type: 'module', eyebrow: 'Operaciones', title: 'Muestreos', detail: 'Resultados y evidencia' },
  'modulo-programa': { type: 'module', eyebrow: 'Operaciones', title: 'Programa de Cosecha', detail: 'Planificación operativa' },
  'modulo-historial': { type: 'module', eyebrow: 'Trazabilidad', title: 'Historial', detail: 'Actividad y responsables' },
  'boton-registrar': { type: 'button', eyebrow: 'Tratos', label: '+ Registrar' },
  'boton-registrar-muestreo': { type: 'button', eyebrow: 'Muestreos', label: '+ Registrar muestreo' },
  'boton-ajustar': { type: 'button', eyebrow: 'Programa de Cosecha', label: 'Ajustar día' },
  'formulario-trato': { type: 'form', eyebrow: 'Nuevo trato', fields: ['Proveedor', 'Producto', 'Toneladas', 'Precio', 'Inicio probable'] },
  'formulario-proveedor-centro': { type: 'form', eyebrow: 'Contexto del muestreo', fields: ['Proveedor', 'Centro'] },
  'formulario-muestreo': { type: 'form', eyebrow: 'Resultados', fields: ['U/Kg', 'Rendimiento', 'Rechazo', 'Condición'] },
  'formulario-programa': { type: 'form', eyebrow: 'Nuevo programa', fields: ['Trato', 'Proveedor', 'Producto'] },
  'formulario-soporte-objetivo': { type: 'form', eyebrow: 'Reportar problema', fields: ['¿Qué intentabas hacer?'] },
  'formulario-soporte-ocurrido': { type: 'form', eyebrow: 'Reportar problema', fields: ['¿Qué ocurrió?'] },
  'formulario-soporte-esperado': { type: 'form', eyebrow: 'Reportar problema', fields: ['¿Qué esperabas que pasara?'] },
  'calculo-trato': { type: 'summary', eyebrow: 'Resumen automático', metrics: ['Responsable: tu usuario', 'Término estimado: calculado'] },
  'resumen-programa': { type: 'summary', eyebrow: 'Resumen del programa', metrics: ['Toneladas', 'Camiones', 'Término estimado'] },
  'calendario-transporte': { type: 'calendar', eyebrow: 'Planificación', days: ['L', 'M', 'M', 'J', 'V'], detail: 'Transporte seleccionado' },
  evidencia: { type: 'upload', eyebrow: 'Evidencia', label: 'Adjuntar imágenes o antecedentes' },
  buscador: { type: 'search', eyebrow: 'Historial', label: 'Buscar proveedor o centro…' },
  actividad: { type: 'timeline', eyebrow: 'Actividad relacionada', items: ['Trato registrado', 'Muestreo guardado', 'Seguimiento actualizado'] },
  filtros: { type: 'chips', eyebrow: 'Filtrar historial', items: ['Fecha', 'Responsable', 'Tipo de evento'] },
  urgencia: { type: 'chips', eyebrow: 'Urgencia', items: ['Baja', 'Media', 'Alta'] },
  guardar: { type: 'button', eyebrow: 'Confirmar información', label: 'Guardar' },
  'guardar-compartir': { type: 'actions', eyebrow: 'Trato registrado', items: ['Guardar', 'Compartir informe'] },
  soporte: { type: 'button', eyebrow: 'Menú lateral', label: 'Reportar problema' },
  'enviar-reporte': { type: 'actions', eyebrow: 'Reporte listo', items: ['Enviar reporte', 'Contexto técnico incluido'] },
};

export const assistantPrompts = [
  { id: 'prompt-trato', label: '¿Cómo creo un trato?', guidedFlowId: 'crear-trato' },
  { id: 'prompt-muestreo', label: '¿Cómo registro un muestreo?', guidedFlowId: 'registrar-muestreo' },
  { id: 'prompt-problema', label: '¿Cómo reporto un problema?', guidedFlowId: 'reportar-problema' },
  { id: 'prompt-sin-muestreo', label: '¿Qué significa “Sin muestreo registrado”?', faqId: 'sin-muestreo' },
  { id: 'prompt-termino', label: '¿Cómo se calcula el término estimado?', faqId: 'termino-estimado' },
];

export const helpSections = [
  {
    id: 'primeros-pasos',
    title: 'Primeros pasos',
    route: null,
    summary: 'Navega por Mitynex, selecciona una empresa y encuentra las funciones principales.',
    whatYouCanDo: ['Moverte entre módulos.', 'Seleccionar una empresa.', 'Buscar proveedores o centros.', 'Reportar problemas.'],
    steps: ['Inicia sesión.', 'Selecciona una empresa si corresponde.', 'Abre un módulo desde el menú lateral.'],
    tips: ['La empresa seleccionada define los datos visibles.'],
    relatedFeatures: ['Menú lateral', 'Selector de empresa', 'Búsqueda global'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/dashboard',
    summary: 'Revisa indicadores, actividad reciente y alertas de la operación.',
    whatYouCanDo: ['Revisar indicadores.', 'Consultar actividad reciente.', 'Identificar alertas.'],
    steps: ['Entra a Dashboard.', 'Revisa indicadores y alertas.', 'Usa los accesos rápidos.'],
    tips: ['Presiona Actualizar para solicitar nuevamente los datos.'],
    relatedFeatures: ['Indicadores', 'Actividad reciente', 'Alertas'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'directorio',
    title: 'Directorio',
    route: '/gestion/proveedores',
    summary: 'Consulta proveedores, contactos y centros para apoyar la gestión.',
    whatYouCanDo: ['Buscar proveedores.', 'Consultar contactos.', 'Revisar centros.'],
    steps: ['Entra a Proveedores.', 'Busca por nombre.', 'Abre el registro para revisar sus datos.'],
    tips: ['Confirma la empresa seleccionada antes de buscar.'],
    relatedFeatures: ['Proveedores', 'Contactos', 'Centros'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'tratos',
    title: 'Tratos',
    route: '/gestion/tratos',
    summary: 'Registra acuerdos comerciales y consulta sus condiciones principales.',
    whatYouCanDo: ['Crear tratos.', 'Registrar toneladas y precio.', 'Compartir informes.'],
    steps: ['Entra a Tratos.', 'Presiona Registrar trato.', 'Completa y guarda la información.'],
    tips: ['El término estimado usa toneladas y camiones por día.'],
    relatedFeatures: ['Responsable automático', 'Término estimado', 'Informe público'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'programa-cosecha',
    title: 'Programa de Cosecha',
    route: '/biomasa/programa',
    summary: 'Organiza la ejecución de tratos acordados en un calendario operativo.',
    whatYouCanDo: ['Crear programas.', 'Definir ritmo diario.', 'Ajustar la planificación.'],
    steps: ['Abre Programa de Cosecha.', 'Selecciona un trato.', 'Define el ritmo y guarda.'],
    tips: ['Revisa saldo y fechas del trato antes de programar.'],
    relatedFeatures: ['Calendario', 'Seguimiento', 'Ajustes diarios'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'muestreos',
    title: 'Muestreos',
    route: '/biomasa/muestreos',
    summary: 'Registra análisis, resultados y evidencia para apoyar decisiones.',
    whatYouCanDo: ['Registrar muestreos.', 'Adjuntar evidencia.', 'Compartir informes.'],
    steps: ['Entra a Muestreos.', 'Selecciona proveedor.', 'Completa análisis y resultado.'],
    tips: ['Usa información verificable y revisa antes de guardar.'],
    relatedFeatures: ['Resultado', 'Evidencia', 'Informe público'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'biomasa',
    title: 'Biomasa',
    route: '/biomasa/status',
    summary: 'Consulta disponibilidad, asignaciones y estado de biomasa.',
    whatYouCanDo: ['Revisar disponibilidad.', 'Consultar asignaciones.', 'Comparar periodos.'],
    steps: ['Entra a Biomasa.', 'Selecciona vista y periodo.', 'Revisa los registros.'],
    tips: ['Mantén tratos, programas y muestreos actualizados.'],
    relatedFeatures: ['Disponibilidad', 'Asignaciones', 'Programas'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'trazabilidad',
    title: 'Trazabilidad',
    route: '/historial',
    summary: 'Revisa qué ocurrió, cuándo ocurrió y quién estuvo asociado.',
    whatYouCanDo: ['Consultar historial.', 'Revisar actividad del equipo.', 'Identificar responsables.'],
    steps: ['Abre Historial.', 'Elige una vista.', 'Busca y revisa el detalle.'],
    tips: ['Registra acciones oportunamente para mantener la trazabilidad.'],
    relatedFeatures: ['Historial', 'Actividad del equipo', 'Sanitario'],
    lastUpdated: '2026-06-10',
  },
  {
    id: 'soporte-tecnico',
    title: 'Soporte técnico',
    route: null,
    summary: 'Reporta problemas y entrega contexto para facilitar su revisión.',
    whatYouCanDo: ['Reportar problemas.', 'Describir lo ocurrido.', 'Entregar contexto útil.'],
    steps: ['Presiona Reportar problema.', 'Describe lo ocurrido.', 'Envía el reporte.'],
    tips: ['Evita incluir información sensible.'],
    relatedFeatures: ['Reporte de problemas', 'Panel de soporte'],
    lastUpdated: '2026-06-10',
  },
];

export const helpFaqs = [
  {
    id: 'proveedor-no-encontrado',
    question: '¿Qué hago si no encuentro un proveedor?',
    answer: 'Confirma la empresa seleccionada, busca usando solo una parte del nombre y revisa la ortografía.',
    relatedSectionId: 'directorio',
  },
  {
    id: 'sin-muestreo',
    question: '¿Qué significa “Sin muestreo registrado”?',
    answer: 'Indica que Mitynex no encuentra un muestreo asociado disponible para ese proveedor o registro.',
    relatedSectionId: 'muestreos',
  },
  {
    id: 'reportar-problema',
    question: '¿Cómo reporto un problema?',
    answer: 'Presiona Reportar problema en la parte inferior del menú lateral y describe qué ocurrió.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'panel-soporte',
    question: '¿Quién puede ver el panel de soporte técnico?',
    answer: 'El panel está disponible únicamente para los roles autorizados definidos por Mitynex.',
    relatedSectionId: 'soporte-tecnico',
  },
  {
    id: 'datos-automaticos',
    question: '¿Por qué algunos datos se calculan automáticamente?',
    answer: 'Mitynex usa los datos registrados para evitar cálculos repetidos y mantener criterios consistentes.',
    relatedSectionId: 'primeros-pasos',
  },
  {
    id: 'termino-estimado',
    question: '¿Cómo se calcula el término estimado de un trato?',
    answer: 'Se estima usando las toneladas registradas y el ritmo de camiones por día.',
    relatedSectionId: 'tratos',
  },
  {
    id: 'significado-trazabilidad',
    question: '¿Qué significa Trazabilidad?',
    answer: 'Es la capacidad de revisar qué ocurrió, cuándo ocurrió y quién estuvo asociado a una acción.',
    relatedSectionId: 'trazabilidad',
  },
];
